import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link"
import Button from "../components/button";

    export default function login() {
        return (
            <div className={styles.container}>
                <Head>
                    <title>Login Page</title>
                    <meta name="description" content="Generated by create next pap" />
                    <link rel="icon" href="/BBB%20logo.png" />
                </Head>

                <main className={styles.main}>
                    <h3 className={styles.title}>
                        Login Here
                    </h3>


                    <p className={styles.description}>
                        Enter Your Email Address to receive an OTP Login Code
                    </p>

                    <form action="/send-data-here" method="post">
                        <label htmlFor="first">Email Address: </label>
                        <input type="email" id="first" name="first"/>
                        <button type="submit">Submit</button>
                    </form>

                    <form action="/send-data-here" method="post">
                        <label htmlFor="otp">OTP Code: </label>
                        <input type="text" id="otp" name="otp"/>
                        <button type="submit">Submit</button>
                    </form>

                    <div className={styles.grid}>
                        <a href="/" className={styles.card}>
                            <h2>Home &rarr;</h2>
                            <p>Take me home tonight!</p>
                        </a>

                        <a href="/register" className={styles.card}>
                            <h2>Register &rarr;</h2>
                            <p>No account? Click here!</p>
                        </a>

                        <a
                            href="https://github.com/vercel/next.js/tree/canary/examples"
                            className={styles.card}
                        >
                            <h2>Examples &rarr;</h2>
                            <p>Discover and deploy boilerplate example Next.js projects.</p>
                        </a>

                        <a
                            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                            className={styles.card}
                        >
                            <h2>Deploy &rarr;</h2>
                            <p>
                                Instantly deploy your Next.js site to a public URL with Vercel.
                            </p>
                        </a>
                    </div>
                </main>

                <footer className={styles.footer}>
                        Powered by Coffee
                </footer>
            </div>
        )
    }
