import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link"
import Button from "../components/button";

export default function register() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Registration</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/BBB%20logo.png" />
            </Head>

            <main className={styles.main}>
                <h3 className={styles.title}>
                    Register Here
                </h3>


                <p className={styles.description}>
                    Let's Get You Started!
                </p>


                <div className={styles.grid}>
                    <a className={styles.card}>
                        <p className={styles.description}>
                            Let's Get You Started!
                        </p>
                        <text>
                            <br />
                        </text>
                        <form action="/send-data-here" method="post">
                            <label htmlFor="first">Email Address: </label>
                            <text><br /><br /></text>
                            <input type="email" id="first" name="first"/>
                            <text><br /><br /></text>
                            <button type="next">Next</button>
                        </form>

                        <text><br /><br /></text>

                        <form action="/send-data-here" method="post">
                            <label htmlFor="first">OTP Code: </label>
                            <text><br /><br /></text>
                            <input type="text" id="first" name="first"/>
                            <text><br /><br /></text>
                            <button type="next">Go!</button>
                        </form>
                    </a>

                    <a href="/login" className={styles.card}>
                        <h2>Login &rarr;</h2>
                        <p>Already have an account? Click here!</p>
                    </a>

                    <a
                        href="https://github.com/vercel/next.js/tree/canary/examples"
                        className={styles.card}
                    >
                        <h2>Examples &rarr;</h2>
                        <p>Discover and deploy boilerplate example Next.js projects.</p>
                    </a>

                    <a
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className={styles.card}
                    >
                        <h2>Deploy &rarr;</h2>
                        <p>
                            Instantly deploy your Next.js site to a public URL with Vercel.
                        </p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                Powered by Coffee
            </footer>
        </div>
    )
}
